import { authOptions } from "@/app/api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth/next";
import UserCard from "@/components/UserCard";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Public Home Page",
  description: "Generated by create next app",
};

export default async function Home() {
  const session = await getServerSession(authOptions);

  return (
    <>
      <div className="text-center">
        {session && <UserCard user={session?.user} pagetype={"Home"} />}
        <h1 className="text-5xl">This is a public page</h1>
      </div>
    </>
  );
}
