import {
  CustomSession,
  authOptions,
} from "@/app/api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth";
import React from "react";
import UserCard from "@/components/UserCard";

import isAuth from "@/utils/isAuth";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Public Home Page",
  description: "Generated by create next app",
};

export default async function AdminDashboard() {
  const session: CustomSession | null = await getServerSession(authOptions);

  const roles: string[] = ["admin"];
  isAuth(session, roles);

  return (
    <div className="text-center">
      {session && <UserCard user={session?.user} pagetype={"Admin"} />}
      <h1 className="text-5xl">This is a Admin page</h1>
    </div>
  );
}
